global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/spring-boot.prod.yml'
        refresh_interval: 5s

  - job_name: 'mongodb'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/mongodb.prod.yml'
        refresh_interval: 5s

  - job_name: 'redis'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/redis.prod.yml'
        refresh_interval: 5s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          environment: 'production'

  - job_name: 'nextjs-app'
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/nextjs.prod.yml'
        refresh_interval: 5s

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/node-exporters.prod.yml'
        refresh_interval: 5s
