version: '3.8'

services:
  redis-pubsub:
    image: redis:7.2
    container_name: redis-pubsub-ktb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_pubsub_data:/data
    networks:
      - redis-pubsub-network

  redis-pubsub-exporter:
    image: oliver006/redis_exporter:v1.66.0
    container_name: redis-pubsub-exporter
    restart: unless-stopped
    ports:
      - "9122:9121"
    environment:
      - REDIS_ADDR=redis://redis-pubsub:6379
    depends_on:
      - redis-pubsub
    networks:
      - redis-pubsub-network

networks:
  redis-pubsub-network:
    driver: bridge

volumes:
  redis_pubsub_data:

